/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package starsimulator;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author Jaden Wickens
 */
public class StarsPanel extends javax.swing.JPanel {

    ArrayList<Star> stars = StarSimulator.getStars();
    ArrayList<Star> namedStars = StarSimulator.getNamedStars();

    /**
     * Creates new form StarsPanel
     */
    public StarsPanel() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        int halfWidth = (this.getWidth() / 2) - 3;
        int halfHeight = (this.getHeight() / 2) - 3;
        for (Star x : stars) {
            g.setColor(Color.white);
            g.fillOval((x.getAdjustedXPos(halfWidth)), (x.getAdjustedYPos(halfHeight)), x.getAdjustedMag(), x.getAdjustedMag());
        }
        for (Constellations x : StarSimulator.getConstilations()) {
            String[] con = x.getStars();
            //System.out.println(con[0]);
            for (int i = 0; i < con.length - 1; i += 2) {
                int firstStarIndex = StarSimulator.findStar(con[i]);
                int secondStarIndex = StarSimulator.findStar(con[i + 1]);
                System.out.println(firstStarIndex + " & " + secondStarIndex);
                if (firstStarIndex > 0 && secondStarIndex > 0) {
                    Star firstStar = namedStars.get(firstStarIndex);
                    Star secondStar = namedStars.get(secondStarIndex);
                    int x1 = firstStar.getAdjustedXPos(halfWidth);
                    int y1 = firstStar.getAdjustedYPos(halfHeight);
                    int x2 = secondStar.getAdjustedXPos(halfWidth);
                    int y2 = secondStar.getAdjustedYPos(halfHeight);
                    g.setColor(Color.red);
                    g.drawLine(x1, y1, x2, y2);
                }
            }
            //System.out.println("i");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
